services:
  jenkins:
    build: .
    container_name: jenkins
    restart: always
    ports:
      - "8081:8080"
      - "50000:50000"
    group_add:
      - "1001"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/web-apps:/home/ubuntu/web-apps
    networks:
      - reseau-web

volumes:
  jenkins_home:

networks:
  reseau-web:
    external: true
